### PR TITLE
Setup instructions for using BlazeGraph in production mode.

### PR DESCRIPTION
**Pull request by gkellogg**
Don't try to seed data if endpoint is not a repository.

### CODE REVIEW

**Comment by gkellogg** [comment]
Looks like it loads okay, but it fails to load application.css/js. Ran with the following:

`SECRET_KEY_BASE=foo SPARQL_URL=http://localhost:9999/bigdata/sparql RAILS_ENV=production bundle exec rails server`

**Comment by jkeck** [comment]
@gkellogg if you're running that locally, try to run `RAILS_ENV rake assets:precompile` before starting the server.  That should compile the js/css into the place that the app will expect it under the production environment.

Presumably in the real-world this will be deployed to a server via capistrano which will take care of this for you.

**Comment by gkellogg** [comment]
Thanks for the tip. My Rails-fu is a bit out of date.

**Comment by gkellogg** [comment]
@jkeck unfortunately, that didn't seem to resolve the issue, but it must be something like that. In any case, it doesn't seem to be an issue with the BlazeGraph setup.

**Pull request merged**
